name: Main Deploy
on:
  push:
    branches:
      - main
      - deploy
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: npm run lint
  # test:
  #   needs:
  #     - lint
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: '18'
  #     - run: npm install
  #     - run: npm run test
  build:
    needs:
      - lint
      # - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: npm run build
  pushDist:
    needs:
      - lint
      # - test
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.COMMIT_TOKEN }}
          publish_dir: ./dist

  deploy:
    needs:
      - lint
      # - test
      - build
      - pushDist
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.RENDER_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{}' \
          ${{ secrets.RENDER_DEPLOY_HOOK }}
